nginx:
    build: nginx
    restart: always
    ports:
        - "80:80"
    links:
        - django
    volumes_from:
        - django:ro
django:
    build: django
    restart: always
    expose:
        - "8000"
    links:
        - mongo
    volumes:
        - ./django/src:/data/src
mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
        - ./data:/data/db
